create table roles(
	role_id INT GENERATED ALWAYS AS IDENTITY,
	role_name VARCHAR(255) NOT NULL,
   	PRIMARY KEY(role_id)
)

create table IF NOT EXISTS users(
	user_id INT GENERATED ALWAYS AS IDENTITY,
	role_id int,
	name varchar(50),
	lastname varchar(50),
	nickname varchar(50) not null,
	rut varchar(10),
	email varchar(120) not null,
	phonenumber varchar(20),
	active boolean default false,
	avatar varchar(255),
	primary key(user_id),
	constraint fk_role
		foreign key (role_id)
			references roles(role_id)
)

create table images(
	image_id INT GENERATED ALWAYS AS IDENTITY,
	image_name varchar(255),
	user_id int,
	primary key(image_id),
	constraint fk_user
		foreign key(user_id)
			references users(user_id)
)

create table attributes(
	attribute_id INT GENERATED ALWAYS AS IDENTITY,
	attribute_servicio varchar(255),
	attribute_price int,
	user_id int,
	primary key(attribute_id),
	constraint fk_user
		foreign key(user_id)
			references users(user_id)
)

CREATE TABLE regions (
  region_id int GENERATED ALWAYS AS IDENTITY,
  region_name varchar(100) DEFAULT NULL,
  PRIMARY KEY (region_id)
) 

INSERT INTO regions (region_name)
VALUES
	('Región Metropolitana'),
	('XV Arica & Parinacota'),
	('I Tarapacá'),
	('II Antofagasta'),
	('III Atacama'),
	('IV Coquimbo'),
	('V Valparaíso'),
	('VI O''Higgins'),
	('VII Maule'),
	('VIII Biobío'),
	('IX Araucanía'),
	('XIV Los Ríos'),
	('X Los Lagos'),
	('XI Aisén'),
	('XII Magallanes & Antártica');
	
CREATE TABLE communes(
  commune_id int GENERATED ALWAYS AS IDENTITY,
  commune_name varchar(100) DEFAULT NULL,
  region_id int,
  PRIMARY KEY (commune_id),
  constraint fk_region
		foreign key(region_id)
			references regions(region_id)
)

INSERT INTO communes ( commune_name, region_id)
VALUES
	('Alhué',1),
	('Buin',1),
	('Calera de Tango',1),
	('Cerrillos',1),
	('Cerro Navia',1),
	('Colina',1),
	('Conchalí',1),
	('Curacaví',1),
	('El Bosque',1),
	('El Monte',1),
	('Estación Central',1),
	('Huechuraba',1),
	('Independencia',1),
	('Isla de Maipo',1),
	('La Cisterna',1),
	('La Florida',1),
	('La Granja',1),
	('La Pintana',1),
	('La Reina',1),
	('Lampa',1),
	('Las Condes',1),
	('Lo Barnechea',1),
	('Lo Espejo',1),
	('Macul',1),
	('Maipú',1),
	('Maria Pinto',1),
	('Melipilla',1),
	('Ñuñoa',1),
	('Padre Hurtado',1),
	('Paine',1),
	('Pedro Aguirre Cerda',1),
	('Peñaflor',1),
	('Peñalolen',1),
	('Pirque',1),
	('Providencia',1),
	('Pudahuel',1),
	('Puente Alto',1),
	('Qulicura',1),
	('Quinta Normal',1),
	('Recoleta',1),
	('Renca',1),
	('San Bernardo',1),
	('San Joaquin',1),
	('San José de Maipo',1),
	('San Miguel',1),
	('San Pedro',1),
	('San Ramón',1),
	('Santiago',1),
	('Talagante',1),
	('Tiltil',1),
	('Vitacura',1),
	('Arica',2),
	('Camarones',2),
	('General lagos',2),
	('Putre',2),
	('Alto Hospicio',3),
	('Camiña',3),
	('Colchane',3),
	('Huara',3),
	('Iquique',3),
	('Pica',3),
	('Pozo Almonte',3),
	('Anrofagasta',4),
	('Calama',4),
	('Maria Elena',4),
	('Mejillones',4),
	('Ollagüe',4),
	('San Pedro de Atacama',4),
	('Sierra Gorda',4),
	('Taltal',4),
	('Tocopilla',4),
	('Alto del Carmen',5),
	('Caldera',5),
	('Chañaral',5),
	('Copiapó',5),
	('Diego de Almagro',5),
	('Freirina',5),
	('Huasco',5),
	('Tierra Amarilla',5),
	('Vallenar',5),
	('Andacollo',6),
	('Canela',6),
	('Combarbalá',6),
	('Coquimbo',6),
	('Illapel',6),
	('La Higuera',6),
	('La Serena',6),
	('Los Vilos',6),
	('Monte Patria',6),
	('Ovalle',6),
	('Paiguano',6),
	('Punitaqui',6),
	('Río Hurtado',6),
	('Salamanca',6),
	('Vicuña',6),
	('Algarrobo',7),
	('Cabildo',7),
	('Calera',7),
	('Calle Larga',7),
	('Cartagena',7),
	('Casanueva',7),
	('Catemu',7),
	('Concón',7),
	('El Quisco',7),
	('El Tabo',7),
	('Hijuelas',7),
	('Isla de Pascua',7),
	('Juan Fernández',7),
	('La Cruz',7),
	('La Ligua',7),
	('Limache',7),
	('Llaillay',7),
	('Los Andes',7),
	('Nogales',7),
	('Olmué',7),
	('Panquehue',7),
	('Papudo',7),
	('Petorca',7),
	('Puchuncaví',7),
	('Putaendo',7),
	('Quillota',7),
	('Quilpué',7),
	('Quintero',7),
	('Rinconada',7),
	('San Antonio',7),
	('San Esteban',7),
	('San Felipe',7),
	('Santa María',7),
	('Santo Domingo',7),
	('Valparaíso',7),
	('Villa Alemana',7),
	('Viña del Mar',7),
	('Zapallar',7),
	('Chépica',8),
	('Chimbarongo',8),
	('Codegua',8),
	('Coinco',8),
	('Coltauco',8),
	('Doñihue',8),
	('Graneros',8),
	('La Estrella',8),
	('Las Cabras',8),
	('Litueche',8),
	('Lolol',8),
	('Machalí',8),
	('Malloa',8),
	('Marchihue',8),
	('Mostazal',8),
	('Nancahua',8),
	('Navidad',8),
	('Olivar',8),
	('Palmilla',8),
	('Paredones',8),
	('Peralillo',8),
	('Peumo',8),
	('Pichidehua',8),
	('Pichilemu',8),
	('Placilla',8),
	('Pumanque',8),
	('Quinta de Tilcoco',8),
	('Rancahua',8),
	('Rengo',8),
	('Requínoa',8),
	('San Fernando',8),
	('San Vicente',8),
	('Santa Cruz',8),
	('Cauquenes',9),
	('Chango',9),
	('Colbún',9),
	('Constitución',9),
	('Curepto',9),
	('Curicó',9),
	('Empedrado',9),
	('Hualañé',9),
	('Licantén',9),
	('Linares',9),
	('Longaví',9),
	('Maule',9),
	('Molina',9),
	('Parral',9),
	('Pelarmo',9),
	('Pelluhue',9),
	('Pencahue',9),
	('Rauco',9),
	('Retiro',9),
	('Rio Claro',9),
	('Romeral',9),
	('Sagrada Familia',9),
	('San Clemente',9),
	('San Javier',9),
	('San Rafael',9),
	('Talca',9),
	('Teno',9),
	('Vichuquén',9),
	('Villa Alegre',9),
	('Yerbas Buenas',9),
	('Alto Bío-Bío',10),
	('Antuco',10),
	('Arauco',10),
	('Bulnes',10),
	('Cabrero',10),
	('Cañete',10),
	('Chiguayante',10),
	('Chillán',10),
	('Chillán Viejo',10),
	('Cobquecura',10),
	('Coelemu',10),
	('Coihueco',10),
	('Concepción',10),
	('Contulmo',10),
	('Coronel',10),
	('Curanilahue',10),
	('El Carmen',10),
	('Florida',10),
	('Hualpén',10),
	('Hualqui',10),
	('Laja',10),
	('Lebu',10),
	('Los Alamos',10),
	('Los Ángeles',10),
	('Lota',10),
	('Mulchén',10),
	('Nacimiento',10),
	('Negrete',10),
	('Ninhue',10),
	('Pemuco',10),
	('Penco',10),
	('Pinto',10),
	('Portezuelo',10),
	('Quillaco',10),
	('Quilleco',10),
	('Quillón',10),
	('Quirihue',10),
	('Ránquil',10),
	('San Carlos',10),
	('San Fabián',10),
	('San Ignacio',10),
	('San Nicolás',10),
	('San Pedro de la Paz',10),
	('San Rosendo',10),
	('Santa Bárbara',10),
	('Santa Juana',10),
	('Talcahuano',10),
	('Tirúa',10),
	('Tomé',10),
	('Treguaco',10),
	('Tucapel',10),
	('Yumbél',10),
	('Yungay',10),
	('Angol',11),
	('Carahue',11),
	('Cholchol',11),
	('Collipulli',11),
	('Cunco',11),
	('Curacautín',11),
	('Curarrehue',11),
	('Ercilla',11),
	('Freire',11),
	('Galvarino',11),
	('Gorbea',11),
	('Lautaro',11),
	('Loncoche',11),
	('Lonquimay',11),
	('Los Sauces',11),
	('Lumaco',11),
	('Melipeuco',11),
	('Nueva Imperial',11),
	('Padre las Casas',11),
	('Perquenco',11),
	('Pitrufquén',11),
	('Pucón',11),
	('Purén',11),
	('Renaico',11),
	('Saavedra',11),
	('Temuco',11),
	('Teodoro Schmidt',11),
	('Toltén',11),
	('Traiguén',11),
	('Victoria',11),
	('Vilcún',11),
	('Villarrica',11),
	('Corral',12),
	('Futrono',12),
	('La Unión',12),
	('Lago Ranco',12),
	('Lanco',12),
	('Los Lagos',12),
	('Máfil',12),
	('Mariquina',12),
	('Paillaco',12),
	('Panguipullo',12),
	('Río Bueno',12),
	('Valdivia',12),
	('Ancud',13),
	('Calbuco',13),
	('Castro',13),
	('Chaitén',13),
	('Chonchoi',13),
	('Cochamó',13),
	('Curaco de Veléz',13),
	('Dalcahue',13),
	('Fresia',13),
	('Frutillar',13),
	('Futaleufú',13),
	('Hualaihué',13),
	('Llanquihue',13),
	('Los Muermos',13),
	('Maullín',13),
	('Osorno',13),
	('Palena',13),
	('Puerto Montt',13),
	('Puerto Octay',13),
	('Puerto Varas',13),
	('Puqueldón',13),
	('Purranque',13),
	('Puyehue',13),
	('Queilén',13),
	('Quellón',13),
	('Quemchi',13),
	('Quincao',13),
	('Río Negro',13),
	('San Juan de la Costa',13),
	('San Pablo',13),
	('Aysen',14),
	('Chile Chico',14),
	('Cisnes',14),
	('Cochrane',14),
	('Coihaique',14),
	('Guaitecas',14),
	('Lago Verde',14),
	('O''Higgins',14),
	('Río Ibañez',14),
	('Tortel',14),
	('Antártica',15),
	('Cabo de Hornos',15),
	('Laguna Blanca',15),
	('Natales',15),
	('Porvenir',15),
	('Primavera',15),
	('Punta Arenas',15),
	('Río Verde',15),
	('San Gregorio',15),
	('Timaukel',15),
	('Torres del Paine',15);

ALTER TABLE users ADD COLUMN commune_id int;
select * from users
select * from communes where commune_name = 'Hualpén'
ALTER TABLE users ADD CONSTRAINT fk_commune FOREIGN KEY (commune_id) REFERENCES communes (commune_id) MATCH FULL;
select * from users
insert into users (role_id,name,lastname,nickname,rut,email,phonenumber,active,commune_id)
values(1,'Ignacio','Ainol','Iggnaxios','178997297','iggnaxios@gmail.com','65163775',true,215)

insert into users (role_id,name,lastname,nickname,rut,email,phonenumber,active,commune_id)
values(3,'Loreto','Perez','Ivannia Hot','178997297','loretohot@gmail.com','65163775',true,215)

delete from users 
where name='Loreto'

ALTER TABLE users
ADD CONSTRAINT uniq_user_email UNIQUE (email);

select * from users